### ISSUE TITLE
"namespace 'reader-macros.core' not found"

### ISSUE THREAD

**Issue by chris-martin** [rufoa/named-re#2]
Trying to use `named-re` in the REPL, Clojure 1.7.0:

```
=> (require 'named-re.core)

CompilerException java.lang.Exception: namespace 'reader-macros.core' not found, compiling:(named_re/core.clj:1:1)
```

**Comment by rufoa** [comment]
Sounds like the reader-macros jar might be missing from your classpath for some reason. Did you add named-re to your project.clj dependencies and run `lein deps`?
